fix(build): delete unnecessary code in prepare-sandbox-release (#6696)
This deletes unneeded checkout, setup-pnpm, and setup-node which should resolve the post-setup-node step failing with:

```
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

This was likely failing because PNPM was never used thus there was nothing to cache for setup-node.